# Use custom format:
format="$directory$git_branch$nodejs$lua$character"

right_format="$time"

# Prompt symbols 
[character]
success_symbol = "[🞈](#a6e3a1 bold)"
error_symbol = "[🞈](#f38ba8)"
vicmd_symbol = "[🞈](#f9e2af)"

[directory]
format = "[]($style)[(fg:#49628a) $path](bg:#89b4fa fg:#49628a)[ ]($style)"
style = "fg:#89b4fa"

[git_branch]
format = "[]($style)[[󰘬 ](bg:#89b4fa fg:#49628a bold)$branch](bg:#89b4fa fg:#4c4f69)[ ]($style)"
style = "fg:#89b4fa"


[nodejs]
format = "[]($style)[[󰎙 ](bg:#89b4fa fg:#49628a bold)$version](bg:#89b4fa fg:#4c4f69)[ ]($style)"
style = "fg:#89b4fa"

[lua]
format = "[]($style)[[󰢱 ](bg:#89b4fa fg:#49628a bold)$version](bg:#89b4fa fg:#4c4f69)[ ]($style)"
style = "fg:#89b4fa"

[time]
format = "$time"
style = "fg:#89b4fa"
